In [1]:
%pip install ipython
%pip install seaborn

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


### importación de librerías

In [2]:
# importación de librerías
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# para pintar
import pylab as plt
import seaborn as sns

#para que salga el grafico
%matplotlib inline

### limpieza csv actor

In [4]:
# importación de csv
df_act_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\actor.csv')

In [7]:
df_act_ori.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [8]:
# copia del df original
df_act=df_act_ori.copy()

In [9]:
df_act.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [17]:
df_act.shape

(200, 4)

In [18]:
df_act_dim_orig=df_act.shape

In [19]:
# info del df
df_act.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   actor_id     200 non-null    int64 
 1   first_name   200 non-null    object
 2   last_name    200 non-null    object
 3   last_update  200 non-null    object
dtypes: int64(1), object(3)
memory usage: 41.0 KB


In [23]:
nan_cols=df_act.isna().sum()

nan_cols[nan_cols>0]

Series([], dtype: int64)

In [24]:
df_act.describe(include='all').T

count unique                  top freq   mean        std  min  \
actor_id     200.0    NaN                  NaN  NaN  100.5  57.879185  1.0   
first_name     200    128             PENELOPE    4    NaN        NaN  NaN   
last_name      200    121               KILMER    5    NaN        NaN  NaN   
last_update    200      1  2006-02-15 04:34:33  200    NaN        NaN  NaN   

               25%    50%     75%    max  
actor_id     50.75  100.5  150.25  200.0  
first_name     NaN    NaN     NaN    NaN  
last_name      NaN    NaN     NaN    NaN  
last_update    NaN    NaN     NaN    NaN

In [25]:
df_act.drop_duplicates().shape==df_act.shape

True

In [26]:
# exploración columna 'actor_id'
df_act.actor_id.head()

0    1
1    2
2    3
3    4
4    5
Name: actor_id, dtype: int64

In [27]:
df_act.actor_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [28]:
df_act.actor_id.value_counts().head()

1      1
138    1
128    1
129    1
130    1
Name: actor_id, dtype: int64

In [29]:
len(df_act.actor_id.value_counts())

200

In [31]:
df_act.head()

actor_id first_name     last_name          last_update
0         1   PENELOPE       GUINESS  2006-02-15 04:34:33
1         2       NICK      WAHLBERG  2006-02-15 04:34:33
2         3         ED         CHASE  2006-02-15 04:34:33
3         4   JENNIFER         DAVIS  2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA  2006-02-15 04:34:33

In [32]:
# exploración y limpieza de columnas del df 
len(df_act.first_name.unique())

128

In [33]:
df_act.first_name.value_counts()

PENELOPE       4
JULIA          4
KENNETH        4
GENE           3
GROUCHO        3
DAN            3
CUBA           3
JAYNE          3
CAMERON        3
FAY            3
CHRISTIAN      3
MATTHEW        3
BURT           3
MORGAN         3
RUSSELL        3
ED             3
NICK           3
MENA           2
ANGELA         2
MARY           2
GARY           2
ADAM           2
SEAN           2
CATE           2
GRETA          2
SCARLETT       2
BEN            2
REESE          2
MINNIE         2
ALBERT         2
SPENCER        2
CHRISTOPHER    2
DARYL          2
CHRIS          2
RENEE          2
SUSAN          2
MERYL          2
FRANCES        2
WARREN         2
AUDREY         2
KEVIN          2
LUCILLE        2
MICHAEL        2
RIP            2
WOODY          2
VIVIEN         2
MILLA          2
KIRSTEN        2
SANDRA         2
HUMPHREY       2
TOM            2
JOHNNY         2
LIZA           1
DEBBIE         1
ROCK           1
GREGORY        1
SALMA          1
LISA           1
JULIANNE      

In [38]:
len(df_act.last_name.unique())

121

In [39]:
df_act.last_name.value_counts().head()

KILMER     5
TEMPLE     4
NOLTE      4
GUINESS    3
ALLEN      3
Name: last_name, dtype: int64

In [40]:
df_act.drop_duplicates(subset = ['first_name','last_name']).shape==df_act.shape

False

In [41]:
df_act['complete_name'] = df_act.first_name + (' ') + df_act.last_name

In [42]:
df_act['complete_name']

0          PENELOPE GUINESS
1             NICK WAHLBERG
2                  ED CHASE
3            JENNIFER DAVIS
4       JOHNNY LOLLOBRIGIDA
5           BETTE NICHOLSON
6              GRACE MOSTEL
7         MATTHEW JOHANSSON
8                 JOE SWANK
9           CHRISTIAN GABLE
10                ZERO CAGE
11               KARL BERRY
12                 UMA WOOD
13            VIVIEN BERGEN
14             CUBA OLIVIER
15             FRED COSTNER
16             HELEN VOIGHT
17                 DAN TORN
18              BOB FAWCETT
19            LUCILLE TRACY
20          KIRSTEN PALTROW
21               ELVIS MARX
22            SANDRA KILMER
23           CAMERON STREEP
24              KEVIN BLOOM
25             RIP CRAWFORD
26            JULIA MCQUEEN
27            WOODY HOFFMAN
28               ALEC WAYNE
29              SANDRA PECK
30           SISSY SOBIESKI
31              TIM HACKMAN
32               MILLA PECK
33           AUDREY OLIVIER
34                JUDY DEAN
35             BURT 

In [43]:
df_act['complete_name'].value_counts().head()

SUSAN DAVIS       2
EWAN GOODING      1
DARYL CRAWFORD    1
GRETA KEITEL      1
JANE JACKMAN      1
Name: complete_name, dtype: int64

In [44]:
df_act[df_act.complete_name == 'SUSAN DAVIS'] # se identifica una actriz repetida. Sólo es 1, de momento la dejamos y no borramos.

actor_id first_name last_name          last_update complete_name
100       101      SUSAN     DAVIS  2006-02-15 04:34:33   SUSAN DAVIS
109       110      SUSAN     DAVIS  2006-02-15 04:34:33   SUSAN DAVIS

In [46]:
df_act.last_update.value_counts() # la columna 'last_update' no aporta info, la borramos.

2006-02-15 04:34:33    200
Name: last_update, dtype: int64

In [47]:
df_act.drop(['last_update'], axis=1, inplace = True)

In [48]:
df_act.head()

actor_id first_name     last_name        complete_name
0         1   PENELOPE       GUINESS     PENELOPE GUINESS
1         2       NICK      WAHLBERG        NICK WAHLBERG
2         3         ED         CHASE             ED CHASE
3         4   JENNIFER         DAVIS       JENNIFER DAVIS
4         5     JOHNNY  LOLLOBRIGIDA  JOHNNY LOLLOBRIGIDA

### limpieza csv category

In [5]:
df_cat_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\category.csv')

In [6]:
df_cat_ori.head()

category_id       name          last_update
0            1     Action  2006-02-15 04:46:27
1            2  Animation  2006-02-15 04:46:27
2            3   Children  2006-02-15 04:46:27
3            4   Classics  2006-02-15 04:46:27
4            5     Comedy  2006-02-15 04:46:27

In [53]:
# copia del df original
df_cat=df_cat_ori.copy()

In [54]:
df_cat.shape

(16, 3)

In [55]:
df_cat_dim_orig=df_cat.shape

In [56]:
# info del df
df_cat.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   category_id  16 non-null     int64 
 1   name         16 non-null     object
 2   last_update  16 non-null     object
dtypes: int64(1), object(2)
memory usage: 2.4 KB


In [57]:
df_cat.columns

Index(['category_id', 'name', 'last_update'], dtype='object')

In [58]:
df_cat.drop_duplicates().shape==df_cat.shape

True

In [60]:
# exploración y limpieza de columnas del df 
df_cat.category_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int64)

In [61]:
df_cat.name.unique()

array(['Action', 'Animation', 'Children', 'Classics', 'Comedy',
       'Documentary', 'Drama', 'Family', 'Foreign', 'Games', 'Horror',
       'Music', 'New', 'Sci-Fi', 'Sports', 'Travel'], dtype=object)

In [62]:
df_cat.name.value_counts()

Action         1
Animation      1
Children       1
Classics       1
Comedy         1
Documentary    1
Drama          1
Family         1
Foreign        1
Games          1
Horror         1
Music          1
New            1
Sci-Fi         1
Sports         1
Travel         1
Name: name, dtype: int64

In [63]:
df_cat.last_update.unique()

array(['2006-02-15 04:46:27'], dtype=object)

In [64]:
df_cat.drop(['last_update'], axis=1, inplace = True)

In [67]:
df_cat.head()

category_id       name
0            1     Action
1            2  Animation
2            3   Children
3            4   Classics
4            5     Comedy

### limpieza csv film

In [7]:
# importación de csv
df_film_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\film.csv')

In [70]:
df_film_ori.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  release_year  \
0  A Epic Drama of a Feminist And a Mad Scientist...          2006   
1  A Astounding Epistle of a Database Administrat...          2006   
2  A Astounding Reflection of a Lumberjack And a ...          2006   
3  A Fanciful Documentary of a Frisbee And a Lumb...          2006   
4  A Fast-Paced Documentary of a Pastry Chef And ...          2006   

   language_id  original_language_id  rental_duration  rental_rate  length  \
0            1                   NaN                6         0.99      86   
1            1                   NaN                3         4.99      48   
2            1                   NaN                7         2.99      50   
3            1                   NaN                5         2.99     117   
4            1                   NaN                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [71]:
df_film=df_film_ori.copy()

In [72]:
df_film.shape

(1000, 13)

In [73]:
df_film_dim_orig=df_film.shape

In [74]:
df_film.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   film_id               1000 non-null   int64  
 1   title                 1000 non-null   object 
 2   description           1000 non-null   object 
 3   release_year          1000 non-null   int64  
 4   language_id           1000 non-null   int64  
 5   original_language_id  0 non-null      float64
 6   rental_duration       1000 non-null   int64  
 7   rental_rate           1000 non-null   float64
 8   length                1000 non-null   int64  
 9   replacement_cost      1000 non-null   float64
 10  rating                1000 non-null   object 
 11  special_features      1000 non-null   object 
 12  last_update           1000 non-null   object 
dtypes: float64(3), int64(5), object(5)
memory usage: 495.3 KB


In [75]:
df_film.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [76]:
df_film.drop_duplicates().shape==df_film.shape

True

In [77]:
df_film.film_id.head()

0    1
1    2
2    3
3    4
4    5
Name: film_id, dtype: int64

In [78]:
df_film.film_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [79]:
len(df_film.film_id.unique())

1000

In [80]:
df_film.film_id.value_counts().head()

1      1
672    1
659    1
660    1
661    1
Name: film_id, dtype: int64

In [81]:
df_film.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [82]:
df_film.title.head()

0    ACADEMY DINOSAUR
1      ACE GOLDFINGER
2    ADAPTATION HOLES
3    AFFAIR PREJUDICE
4         AFRICAN EGG
Name: title, dtype: object

In [83]:
df_film.title.unique()

array(['ACADEMY DINOSAUR', 'ACE GOLDFINGER', 'ADAPTATION HOLES',
       'AFFAIR PREJUDICE', 'AFRICAN EGG', 'AGENT TRUMAN',
       'AIRPLANE SIERRA', 'AIRPORT POLLOCK', 'ALABAMA DEVIL',
       'ALADDIN CALENDAR', 'ALAMO VIDEOTAPE', 'ALASKA PHANTOM',
       'ALI FOREVER', 'ALICE FANTASIA', 'ALIEN CENTER', 'ALLEY EVOLUTION',
       'ALONE TRIP', 'ALTER VICTORY', 'AMADEUS HOLY',
       'AMELIE HELLFIGHTERS', 'AMERICAN CIRCUS', 'AMISTAD MIDSUMMER',
       'ANACONDA CONFESSIONS', 'ANALYZE HOOSIERS', 'ANGELS LIFE',
       'ANNIE IDENTITY', 'ANONYMOUS HUMAN', 'ANTHEM LUKE',
       'ANTITRUST TOMATOES', 'ANYTHING SAVANNAH', 'APACHE DIVINE',
       'APOCALYPSE FLAMINGOS', 'APOLLO TEEN', 'ARABIA DOGMA',
       'ARACHNOPHOBIA ROLLERCOASTER', 'ARGONAUTS TOWN', 'ARIZONA BANG',
       'ARK RIDGEMONT', 'ARMAGEDDON LOST', 'ARMY FLINTSTONES',
       'ARSENIC INDEPENDENCE', 'ARTIST COLDBLOODED', 'ATLANTIS CAUSE',
       'ATTACKS HATE', 'ATTRACTION NEWTON', 'AUTUMN CROW', 'BABY HALL',
       'BACKLASH UND

In [84]:
df_film.title.value_counts()

ACADEMY DINOSAUR               1
PERFECT GROOVE                 1
PARK CITIZEN                   1
PARTY KNOCK                    1
PAST SUICIDES                  1
PATHS CONTROL                  1
PATIENT SISTER                 1
PATRIOT ROMAN                  1
PATTON INTERVIEW               1
PAYCHECK WAIT                  1
PEACH INNOCENT                 1
PEAK FOREVER                   1
PEARL DESTINY                  1
PELICAN COMFORTS               1
PERDITION FARGO                1
PERSONAL LADYBUGS              1
POLISH BROOKLYN                1
PET HAUNTING                   1
PHANTOM GLORY                  1
PHILADELPHIA WIFE              1
PIANIST OUTFIELD               1
PICKUP DRIVING                 1
PILOT HOOSIERS                 1
PINOCCHIO SIMON                1
PIRATES ROXANNE                1
PITTSBURGH HUNCHBACK           1
PITY BOUND                     1
PIZZA JUMANJI                  1
PLATOON INSTINCT               1
PLUTO OLEANDER                 1
PARIS WEEK

In [85]:
len(df_film.title.value_counts())

1000

In [86]:
df_film.columns

Index(['film_id', 'title', 'description', 'release_year', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [87]:
df_film.description.head()

0    A Epic Drama of a Feminist And a Mad Scientist...
1    A Astounding Epistle of a Database Administrat...
2    A Astounding Reflection of a Lumberjack And a ...
3    A Fanciful Documentary of a Frisbee And a Lumb...
4    A Fast-Paced Documentary of a Pastry Chef And ...
Name: description, dtype: object

In [95]:
df_film.description.unique()

array(['A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies',
       'A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China',
       'A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory',
       'A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank',
       'A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico',
       'A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China',
       'A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat',
       'A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India',
       'A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat',
       'A Action-Packed Tale of a Man 

In [98]:
df_film.description.value_counts().head()

A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies                   1
A Thrilling Yarn of a Dog And a Dog who must Build a Husband in A Baloon                                           1
A Taut Epistle of a Sumo Wrestler And a Girl who must Face a Husband in Ancient Japan                              1
A Fateful Display of a Technical Writer And a Butler who must Battle a Sumo Wrestler in An Abandoned Mine Shaft    1
A Intrepid Tale of a Madman And a Astronaut who must Challenge a Hunter in A Monastery                             1
Name: description, dtype: int64

In [99]:
df_film.release_year.head()

0    2006
1    2006
2    2006
3    2006
4    2006
Name: release_year, dtype: int64

In [100]:
df_film.drop(['release_year'], axis=1, inplace = True)

In [102]:
df_film.columns

Index(['film_id', 'title', 'description', 'language_id',
       'original_language_id', 'rental_duration', 'rental_rate', 'length',
       'replacement_cost', 'rating', 'special_features', 'last_update'],
      dtype='object')

In [103]:
df_film.language_id.head()

0    1
1    1
2    1
3    1
4    1
Name: language_id, dtype: int64

In [104]:
df_film.language_id.unique()

array([1], dtype=int64)

In [105]:
df_film.language_id.value_counts()

1    1000
Name: language_id, dtype: int64

In [106]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   original_language_id  rental_duration  rental_rate  length  \
0                   NaN                6         0.99      86   
1                   NaN                3         4.99      48   
2                   NaN                7         2.99      50   
3                   NaN                5         2.99     117   
4                   NaN                6         2.99     130   

   replacement_cost rating                  special_features  \
0             20.99     PG  Deleted Scenes,Behind the Scenes   
1             12.99      G           Trailers,Deleted Scenes   
2             18.99  NC-17           Trailers,Deleted Scenes   
3             26.99      G    Commentaries,Behind the Scenes   
4             22.99      G                    Deleted Scenes   

           last_update  
0  2006-02-15 05:03:42  
1  2006-02-15 05:03:42  
2  2006-02-15 05:03:42  
3  2006-02-15 05:03:42  
4  2006-02-15 05:03:42

In [107]:
df_film.original_language_id.unique()

array([nan])

In [108]:
df_film.drop(['original_language_id'], axis=1, inplace = True)

In [109]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features          last_update  
0  Deleted Scenes,Behind the Scenes  2006-02-15 05:03:42  
1           Trailers,Deleted Scenes  2006-02-15 05:03:42  
2           Trailers,Deleted Scenes  2006-02-15 05:03:42  
3    Commentaries,Behind the Scenes  2006-02-15 05:03:42  
4                    Deleted Scenes  2006-02-15 05:03:42

In [110]:
df_film.rental_duration.unique()

array([6, 3, 7, 5, 4], dtype=int64)

In [111]:
df_film.rental_duration.value_counts()

6    212
3    203
4    203
7    191
5    191
Name: rental_duration, dtype: int64

In [112]:
df_film.length.unique()

array([ 86,  48,  50, 117, 130, 169,  62,  54, 114,  63, 126, 136, 150,
        94,  46, 180,  82,  57, 113,  79, 129,  85,  92, 181,  74, 179,
        91, 168, 119, 153, 147, 127, 121,  68,  99, 148, 137, 170,  83,
       108, 118, 162, 182,  75, 173,  87,  65,  90, 122, 160,  89, 175,
       106,  73, 151, 100,  53,  77, 142,  93, 163, 103,  61,  71, 102,
        76,  98,  72, 176, 123,  56, 161,  60, 133, 125,  67,  52, 120,
       167,  70, 135, 112, 183, 110, 152,  51, 146,  66, 185, 124, 107,
       101, 132, 143, 165,  81, 164,  58,  95, 139,  55, 149, 109,  59,
       172, 115, 184, 166,  64, 104,  69,  84, 144,  88, 141,  47,  49,
       177, 154, 159, 178,  96, 116, 171, 140, 155, 158, 174, 138,  97,
       131, 156,  80, 145, 111, 128, 157,  78, 105, 134], dtype=int64)

In [113]:
df_film.length.value_counts().head()

85     17
179    13
112    13
84     13
73     12
Name: length, dtype: int64

In [114]:
df_film.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   film_id           1000 non-null   int64  
 1   title             1000 non-null   object 
 2   description       1000 non-null   object 
 3   language_id       1000 non-null   int64  
 4   rental_duration   1000 non-null   int64  
 5   rental_rate       1000 non-null   float64
 6   length            1000 non-null   int64  
 7   replacement_cost  1000 non-null   float64
 8   rating            1000 non-null   object 
 9   special_features  1000 non-null   object 
 10  last_update       1000 non-null   object 
dtypes: float64(2), int64(4), object(5)
memory usage: 479.7 KB


In [115]:
df_film.replacement_cost.unique()

array([20.99, 12.99, 18.99, 26.99, 22.99, 17.99, 28.99, 15.99, 21.99,
       24.99, 16.99, 23.99, 10.99, 14.99, 27.99,  9.99, 19.99, 11.99,
       29.99, 25.99, 13.99])

In [116]:
df_film.replacement_cost.value_counts().head()

20.99    57
22.99    55
12.99    55
21.99    55
13.99    55
Name: replacement_cost, dtype: int64

In [117]:
df_film.rating.unique()

array(['PG', 'G', 'NC-17', 'PG-13', 'R'], dtype=object)

In [118]:
df_film.rating.value_counts()

PG-13    223
NC-17    210
R        195
PG       194
G        178
Name: rating, dtype: int64

In [119]:
df_film.special_features.unique()

array(['Deleted Scenes,Behind the Scenes', 'Trailers,Deleted Scenes',
       'Commentaries,Behind the Scenes', 'Deleted Scenes', 'Trailers',
       'Commentaries,Deleted Scenes',
       'Trailers,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Behind the Scenes', 'Trailers,Commentaries',
       'Trailers,Behind the Scenes',
       'Commentaries,Deleted Scenes,Behind the Scenes',
       'Trailers,Commentaries,Deleted Scenes',
       'Trailers,Commentaries,Deleted Scenes,Behind the Scenes',
       'Behind the Scenes', 'Commentaries'], dtype=object)

In [120]:
df_film.special_features.value_counts()

Trailers,Commentaries,Behind the Scenes                   79
Trailers                                                  72
Trailers,Commentaries                                     72
Trailers,Behind the Scenes                                72
Deleted Scenes,Behind the Scenes                          71
Commentaries,Behind the Scenes                            70
Behind the Scenes                                         70
Trailers,Deleted Scenes                                   66
Commentaries,Deleted Scenes,Behind the Scenes             66
Commentaries,Deleted Scenes                               65
Trailers,Commentaries,Deleted Scenes                      64
Commentaries                                              62
Deleted Scenes                                            61
Trailers,Commentaries,Deleted Scenes,Behind the Scenes    61
Trailers,Deleted Scenes,Behind the Scenes                 49
Name: special_features, dtype: int64

In [121]:
df_film.last_update.unique()

array(['2006-02-15 05:03:42'], dtype=object)

In [122]:
df_film.drop(['last_update'], axis=1, inplace = True)

In [123]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

### limpieza csv inventory

In [125]:
df_inv_ori = pd.read_csv(r'C:\Users\david\Proyectos\w3-database-project\data\inventory.csv')

In [126]:
df_inv_ori.head()

inventory_id  film_id  store_id          last_update
0             1        1         1  2006-02-15 05:09:17
1             2        1         1  2006-02-15 05:09:17
2             3        1         1  2006-02-15 05:09:17
3             4        1         1  2006-02-15 05:09:17
4             5        1         2  2006-02-15 05:09:17

In [127]:
df_inv=df_inv_ori.copy()

In [128]:
df_inv.shape

(1000, 4)

In [129]:
df_finv_dim_orig=df_inv.shape

In [130]:
df_inv.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   inventory_id  1000 non-null   int64 
 1   film_id       1000 non-null   int64 
 2   store_id      1000 non-null   int64 
 3   last_update   1000 non-null   object
dtypes: int64(3), object(1)
memory usage: 97.8 KB


In [131]:
df_inv.drop_duplicates().shape==df_inv.shape

True

In [132]:
df_inv.inventory_id.value_counts()

1       1
672     1
659     1
660     1
661     1
662     1
663     1
664     1
665     1
666     1
667     1
668     1
669     1
670     1
671     1
673     1
688     1
674     1
675     1
676     1
677     1
678     1
679     1
680     1
681     1
682     1
683     1
684     1
685     1
686     1
658     1
657     1
656     1
655     1
628     1
629     1
630     1
631     1
632     1
633     1
634     1
635     1
636     1
637     1
638     1
639     1
640     1
641     1
642     1
643     1
644     1
645     1
646     1
647     1
648     1
649     1
650     1
651     1
652     1
653     1
654     1
687     1
689     1
2       1
735     1
722     1
723     1
724     1
725     1
726     1
727     1
728     1
729     1
730     1
731     1
732     1
733     1
734     1
736     1
690     1
737     1
738     1
739     1
740     1
741     1
742     1
743     1
744     1
745     1
746     1
747     1
748     1
749     1
721     1
720     1
719     1
718     1
691     1
692     1
693     1


In [133]:
len(df_inv.inventory_id.value_counts())

1000

In [134]:
df_inv.film_id.value_counts()

1      8
127    8
73     8
174    8
86     8
193    8
91     8
199    8
200    8
103    8
69     8
206    8
31     8
109    8
220    8
12     7
172    7
57     7
143    7
43     7
10     7
154    7
39     7
37     7
35     7
11     7
218    7
112    7
159    7
114    7
115    7
78     7
162    7
4      7
22     7
119    7
181    7
135    7
122    7
167    7
166    6
129    6
170    6
90     6
79     6
77     6
89     6
101    6
139    6
132    6
97     6
131    6
130    6
99     6
100    6
150    6
149    6
116    6
117    6
118    6
147    6
121    6
72     6
176    6
21     6
61     6
49     6
204    6
215    6
51     6
15     6
55     6
17     6
18     6
191    6
45     6
222    6
6      6
67     6
25     6
189    6
19     6
183    6
105    5
155    5
175    5
23     5
26     5
141    5
142    5
44     5
123    5
212    5
216    5
138    5
9      5
59     5
74     5
173    5
184    5
140    5
7      5
83     5
56     5
158    5
165    5
54     5
164    5
160    5
50     5
95     5
2

In [135]:
df_inv.store_id.value_counts()

1    503
2    497
Name: store_id, dtype: int64

In [136]:
df_inv.last_update.value_counts()

2006-02-15 05:09:17    1000
Name: last_update, dtype: int64

In [137]:
df_inv.drop(['last_update'], axis=1, inplace = True)

In [138]:
df_inv.head()

inventory_id  film_id  store_id
0             1        1         1
1             2        1         1
2             3        1         1
3             4        1         1
4             5        1         2

### limpieza csv language

In [8]:
df_lang_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\language.csv')

In [140]:
df_lang_ori

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

In [146]:
df_lang=df_lang_ori.copy()

In [147]:
df_lang.shape

(6, 3)

In [148]:
df_lang_dim_orig=df_lang.shape

In [149]:
df_lang.drop(['last_update'], axis=1, inplace = True)

In [150]:
df_lang_ori

language_id      name          last_update
0            1   English  2006-02-15 05:02:19
1            2   Italian  2006-02-15 05:02:19
2            3  Japanese  2006-02-15 05:02:19
3            4  Mandarin  2006-02-15 05:02:19
4            5    French  2006-02-15 05:02:19
5            6    German  2006-02-15 05:02:19

### limpieza csv rental

In [9]:
df_ren_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\rental.csv')

In [153]:
df_ren_ori.head()

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id          last_update  
0  2005-05-26 22:04:30         1  2006-02-15 21:30:53  
1  2005-05-28 19:40:33         1  2006-02-15 21:30:53  
2  2005-06-01 22:12:39         1  2006-02-15 21:30:53  
3  2005-06-03 01:43:41         2  2006-02-15 21:30:53  
4  2005-06-02 04:33:21         1  2006-02-15 21:30:53

In [154]:
df_ren=df_ren_ori.copy()

In [155]:
df_ren.shape

(1000, 7)

In [156]:
df_ren_dim_orig=df_ren.shape

In [157]:
df_ren.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   rental_id     1000 non-null   int64 
 1   rental_date   1000 non-null   object
 2   inventory_id  1000 non-null   int64 
 3   customer_id   1000 non-null   int64 
 4   return_date   1000 non-null   object
 5   staff_id      1000 non-null   int64 
 6   last_update   1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 254.0 KB


In [158]:
df_ren.drop_duplicates().shape==df_ren.shape

True

In [159]:
df_ren.rental_id.value_counts()

1       1
673     1
660     1
661     1
662     1
663     1
664     1
665     1
666     1
667     1
668     1
669     1
670     1
671     1
672     1
674     1
689     1
675     1
676     1
677     1
678     1
679     1
680     1
681     1
682     1
683     1
684     1
685     1
686     1
687     1
659     1
658     1
657     1
656     1
629     1
630     1
631     1
632     1
633     1
634     1
635     1
636     1
637     1
638     1
639     1
640     1
641     1
642     1
643     1
644     1
645     1
646     1
647     1
648     1
649     1
650     1
651     1
652     1
653     1
654     1
655     1
688     1
690     1
2       1
736     1
723     1
724     1
725     1
726     1
727     1
728     1
729     1
730     1
731     1
732     1
733     1
734     1
735     1
737     1
691     1
738     1
739     1
740     1
741     1
742     1
743     1
744     1
745     1
746     1
747     1
748     1
749     1
750     1
722     1
721     1
720     1
719     1
692     1
693     1
694     1


In [160]:
df_ren.rental_date.value_counts()

2005-05-30 14:47:31    2
2005-05-28 22:07:30    1
2005-05-28 20:53:31    1
2005-05-28 21:01:25    1
2005-05-28 21:09:31    1
2005-05-28 21:23:02    1
2005-05-28 21:31:08    1
2005-05-28 21:38:39    1
2005-05-28 21:48:51    1
2005-05-28 21:49:02    1
2005-05-28 21:54:45    1
2005-05-28 22:03:25    1
2005-05-28 22:04:03    1
2005-05-28 22:04:30    1
2005-05-28 22:05:29    1
2005-05-28 22:11:35    1
2005-05-29 00:45:24    1
2005-05-28 22:22:44    1
2005-05-28 22:27:51    1
2005-05-28 23:00:08    1
2005-05-28 23:15:48    1
2005-05-28 23:24:57    1
2005-05-28 23:27:26    1
2005-05-28 23:39:44    1
2005-05-28 23:53:18    1
2005-05-29 00:09:48    1
2005-05-29 00:13:15    1
2005-05-29 00:17:51    1
2005-05-29 00:27:10    1
2005-05-29 00:32:09    1
2005-05-28 20:27:53    1
2005-05-24 22:53:30    1
2005-05-28 20:23:09    1
2005-05-28 20:18:24    1
2005-05-28 17:19:15    1
2005-05-28 17:24:51    1
2005-05-28 17:36:32    1
2005-05-28 17:37:50    1
2005-05-28 17:37:59    1
2005-05-28 17:40:35    1


In [161]:
df_ren.inventory_id.value_counts()

367     1
1769    1
1414    1
2247    1
2968    1
3997    1
87      1
1012    1
3075    1
797     1
3528    1
3677    1
227     1
1027    1
697     1
1150    1
742     1
1273    1
2329    1
4558    1
3741    1
907     1
4147    1
3346    1
3160    1
2038    1
3242    1
1385    1
2441    1
1731    1
1382    1
3226    1
848     1
2846    1
1527    1
1254    1
2465    1
1287    1
58      1
2630    1
1648    1
4213    1
1581    1
2685    1
4204    1
495     1
3548    1
140     1
3105    1
4304    1
3128    1
1922    1
3435    1
3476    1
1781    1
4384    1
739     1
1201    1
126     1
2312    1
331     1
4135    1
2646    1
1525    1
3689    1
3407    1
3770    1
4088    1
933     1
1629    1
242     1
1688    1
3473    1
4124    1
2530    1
2951    1
3084    1
3421    1
769     1
4034    1
2284    1
1183    1
600     1
3189    1
273     1
2528    1
3722    1
581     1
4272    1
1993    1
2803    1
1146    1
730     1
4540    1
1116    1
3687    1
267     1
800     1
635     1
592     1


In [162]:
df_ren.customer_id.value_counts()

197    8
245    6
596    6
274    6
371    6
19     6
575    5
207    5
391    5
528    5
44     5
53     5
161    5
506    5
468    5
269    5
77     5
429    5
14     5
105    4
256    4
176    4
569    4
313    4
250    4
368    4
159    4
296    4
551    4
246    4
109    4
56     4
472    4
375    4
288    4
198    4
400    4
311    4
307    4
249    4
7      4
469    4
369    4
261    4
535    4
222    4
502    4
239    4
184    3
319    3
247    3
22     3
412    3
439    3
240    3
337    3
437    3
584    3
185    3
134    3
46     3
500    3
201    3
503    3
242    3
84     3
196    3
54     3
436    3
446    3
304    3
60     3
549    3
401    3
408    3
533    3
16     3
50     3
231    3
47     3
473    3
548    3
432    3
482    3
399    3
452    3
357    3
142    3
89     3
354    3
257    3
102    3
504    3
384    3
204    3
374    3
119    3
442    3
387    3
460    3
58     3
48     3
154    3
150    3
17     3
162    3
323    3
359    3
484    3
131    3
167    3
6

In [165]:
df_ren.return_date.value_counts().head()

2005-06-05 15:16:54    2
2005-06-03 06:05:10    2
2005-06-06 06:23:00    2
2005-05-26 22:04:30    1
2005-05-30 15:26:31    1
Name: return_date, dtype: int64

In [166]:
df_ren.staff_id.value_counts()

2    521
1    479
Name: staff_id, dtype: int64

In [167]:
df_ren.last_update.value_counts()

2006-02-15 21:30:53    1000
Name: last_update, dtype: int64

In [168]:
df_ren.drop(['last_update'], axis=1, inplace = True)

In [169]:
df_ren.head()

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id  
0  2005-05-26 22:04:30         1  
1  2005-05-28 19:40:33         1  
2  2005-06-01 22:12:39         1  
3  2005-06-03 01:43:41         2  
4  2005-06-02 04:33:21         1

### limpieza csv old_HDD

In [10]:
df_old_ori = pd.read_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data\old_HDD.csv')

In [171]:
df_old_ori.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [172]:
df_old=df_old_ori.copy()

In [173]:
df_old.shape

(1000, 5)

In [174]:
df_old_dim_orig=df_old.shape

In [175]:
df_old.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   first_name    1000 non-null   object
 1   last_name     1000 non-null   object
 2   title         1000 non-null   object
 3   release_year  1000 non-null   int64 
 4   category_id   1000 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 207.6 KB


In [176]:
df_old.drop_duplicates().shape==df_old.shape

True

In [177]:
df_old.first_name.unique()

array(['PENELOPE', 'NICK', 'ED', 'JENNIFER', 'JOHNNY', 'BETTE', 'GRACE',
       'MATTHEW', 'JOE', 'CHRISTIAN', 'ZERO', 'KARL', 'UMA', 'VIVIEN',
       'CUBA', 'FRED', 'HELEN', 'DAN', 'BOB', 'LUCILLE', 'KIRSTEN',
       'ELVIS', 'SANDRA', 'CAMERON', 'KEVIN', 'RIP', 'JULIA', 'WOODY',
       'ALEC', 'SISSY', 'TIM', 'MILLA', 'AUDREY', 'JUDY', 'BURT', 'VAL',
       'TOM', 'GOLDIE'], dtype=object)

In [178]:
df_old.first_name.value_counts()

SANDRA       56
VAL          35
UMA          35
JULIA        33
RIP          33
HELEN        32
KARL         31
WOODY        31
VIVIEN       30
LUCILLE      30
GRACE        30
JOHNNY       29
BURT         29
ALEC         29
CUBA         28
KIRSTEN      27
FRED         27
ELVIS        26
ZERO         25
BOB          25
NICK         25
AUDREY       25
JOE          25
TOM          25
MILLA        24
CAMERON      24
TIM          23
DAN          22
ED           22
JENNIFER     22
CHRISTIAN    22
KEVIN        21
MATTHEW      20
BETTE        20
PENELOPE     19
SISSY        18
JUDY         15
GOLDIE        7
Name: first_name, dtype: int64

In [179]:
df_old.last_name.unique()

array(['GUINESS', 'WAHLBERG', 'CHASE', 'DAVIS', 'LOLLOBRIGIDA',
       'NICHOLSON', 'MOSTEL', 'JOHANSSON', 'SWANK', 'GABLE', 'CAGE',
       'BERRY', 'WOOD', 'BERGEN', 'OLIVIER', 'COSTNER', 'VOIGHT', 'TORN',
       'FAWCETT', 'TRACY', 'PALTROW', 'MARX', 'KILMER', 'STREEP', 'BLOOM',
       'CRAWFORD', 'MCQUEEN', 'HOFFMAN', 'WAYNE', 'PECK', 'SOBIESKI',
       'HACKMAN', 'DEAN', 'DUKAKIS', 'BOLGER', 'MCKELLEN', 'BRODY'],
      dtype=object)

In [180]:
df_old.last_name.value_counts()

OLIVIER         53
PECK            43
KILMER          37
BOLGER          35
WOOD            35
MCQUEEN         33
CRAWFORD        33
VOIGHT          32
BERRY           31
HOFFMAN         31
BERGEN          30
MOSTEL          30
TRACY           30
WAYNE           29
DUKAKIS         29
LOLLOBRIGIDA    29
PALTROW         27
COSTNER         27
MARX            26
MCKELLEN        25
SWANK           25
WAHLBERG        25
CAGE            25
FAWCETT         25
STREEP          24
HACKMAN         23
GABLE           22
DAVIS           22
TORN            22
CHASE           22
BLOOM           21
NICHOLSON       20
JOHANSSON       20
GUINESS         19
SOBIESKI        18
DEAN            15
BRODY            7
Name: last_name, dtype: int64

In [181]:
df_old.drop_duplicates(subset = ['first_name', 'title', 'last_name']).shape==df_old.shape

True

In [182]:
df_old.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [183]:
df_old.title.unique()

array(['ACADEMY DINOSAUR', 'ANACONDA CONFESSIONS', 'ANGELS LIFE',
       'BULWORTH COMMANDMENTS', 'CHEAPER CLYDE', 'COLOR PHILADELPHIA',
       'ELEPHANT TROJAN', 'GLEAMING JAWBREAKER', 'HUMAN GRAFFITI',
       'KING EVOLUTION', 'LADY STAGE', 'LANGUAGE COWBOY',
       'MULHOLLAND BEAST', 'OKLAHOMA JUMANJI', 'RULES HUMAN',
       'SPLASH GUMP', 'VERTIGO NORTHWEST', 'WESTWARD SEABISCUIT',
       'WIZARD COLDBLOODED', 'ADAPTATION HOLES', 'APACHE DIVINE',
       'BABY HALL', 'BULL SHAWSHANK', 'CHAINSAW UPTOWN',
       'CHISUM BEHAVIOR', 'DESTINY SATURDAY', 'DRACULA CRYSTAL',
       'FIGHT JAWBREAKER', 'FLASH WARS', 'GILBERT PELICAN',
       'GOODFELLAS SALUTE', 'HAPPINESS UNITED', 'INDIAN LOVE',
       'JEKYLL FROGMEN', 'JERSEY SASSY', 'LIAISONS SWEET', 'LUCKY FLYING',
       'MAGUIRE APACHE', 'MALLRATS UNITED', 'MASK PEACH', 'ROOF CHAMPION',
       'RUSHMORE MERMAID', 'SMILE EARRING', 'WARDROBE PHANTOM',
       'ALONE TRIP', 'ARMY FLINTSTONES', 'ARTIST COLDBLOODED',
       'BOONDOCK BALLR

In [184]:
len(df_old.title.unique())

614

In [185]:
len(df_film.title.unique())

1000

In [186]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [190]:
lst = []

for i in range (len(df_old)):
    for j in range (len(df_film)):
        if df_old.loc[i, 'title'] == df_film.loc[j, 'title']:
            lst.append(df_film.loc[j, 'film_id'])
            break
            
lst[:10]

[1, 23, 25, 106, 140, 166, 277, 361, 438, 499]

In [191]:
len(df_old)

1000

In [192]:
len(lst)

1000

In [193]:
df_old.head()

first_name last_name                  title  release_year  category_id
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14

In [194]:
df_old['film_id'] = lst

In [195]:
df_old.head()

first_name last_name                  title  release_year  category_id  \
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6   
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2   
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13   
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10   
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14   

   film_id  
0        1  
1       23  
2       25  
3      106  
4      140

In [197]:
df_old.release_year.value_counts()

2006    1000
Name: release_year, dtype: int64

In [198]:
df_old.category_id.value_counts()

15    79
1     77
2     75
7     74
13    73
6     72
11    64
9     64
3     62
14    58
8     57
4     55
12    54
16    52
5     46
10    38
Name: category_id, dtype: int64

In [199]:
df_old.head()

first_name last_name                  title  release_year  category_id  \
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6   
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2   
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13   
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10   
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14   

   film_id  
0        1  
1       23  
2       25  
3      106  
4      140

In [200]:
df_act.head()

actor_id first_name     last_name        complete_name
0         1   PENELOPE       GUINESS     PENELOPE GUINESS
1         2       NICK      WAHLBERG        NICK WAHLBERG
2         3         ED         CHASE             ED CHASE
3         4   JENNIFER         DAVIS       JENNIFER DAVIS
4         5     JOHNNY  LOLLOBRIGIDA  JOHNNY LOLLOBRIGIDA

In [201]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [202]:
df_cat.head()

category_id       name
0            1     Action
1            2  Animation
2            3   Children
3            4   Classics
4            5     Comedy

In [203]:
df_old['complete_name'] = df_old.first_name + ' ' + df_old.last_name 

In [204]:
df_old.head()

first_name last_name                  title  release_year  category_id  \
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6   
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2   
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13   
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10   
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14   

   film_id     complete_name  
0        1  PENELOPE GUINESS  
1       23  PENELOPE GUINESS  
2       25  PENELOPE GUINESS  
3      106  PENELOPE GUINESS  
4      140  PENELOPE GUINESS

In [205]:
len(df_old)

1000

In [206]:
df_act.head()

actor_id first_name     last_name        complete_name
0         1   PENELOPE       GUINESS     PENELOPE GUINESS
1         2       NICK      WAHLBERG        NICK WAHLBERG
2         3         ED         CHASE             ED CHASE
3         4   JENNIFER         DAVIS       JENNIFER DAVIS
4         5     JOHNNY  LOLLOBRIGIDA  JOHNNY LOLLOBRIGIDA

In [207]:
len(df_act)

200

In [209]:
lst1 = []

for i in range (len(df_old)):
    for j in range (len(df_act)):
        if df_old.loc[i, 'complete_name'] == df_act.loc[j, 'complete_name']:
            lst1.append(df_act.loc[j, 'actor_id'])
            break
            
lst1[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [210]:
df_old['actor_id'] = lst1

In [211]:
df_old.head()

first_name last_name                  title  release_year  category_id  \
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6   
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2   
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13   
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10   
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14   

   film_id     complete_name  actor_id  
0        1  PENELOPE GUINESS         1  
1       23  PENELOPE GUINESS         1  
2       25  PENELOPE GUINESS         1  
3      106  PENELOPE GUINESS         1  
4      140  PENELOPE GUINESS         1

### Revisión de columnas similares en los diferentes df

In [234]:
df_film.film_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [235]:
df_inv.film_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  34,  35,  37,  39,  40,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
        98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 172, 173, 174, 175, 176, 177, 178, 179, 180,
       181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 19

In [236]:
df_inv.inventory_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [241]:
df_inv.inventory_id.value_counts().head()

1      1
672    1
659    1
660    1
661    1
Name: inventory_id, dtype: int64

In [238]:
len(df_inv.inventory_id.unique())

1000

In [239]:
len(df_ren.inventory_id.unique())

1000

In [237]:
df_ren.inventory_id.unique()

array([ 367, 1525, 1711, 2452, 2079, 2792, 3995, 2346, 2580, 1824, 4443,
       1584, 2294, 2701, 3049,  389,  830, 3376, 1941, 3517,  146,  727,
       4441, 3273, 3961, 4371, 1225, 4068,  611, 3744, 4482, 3832, 1681,
       2613, 1286, 1308,  403, 2540, 4466, 2638, 1761,  380, 2578, 3098,
       1853, 3318, 2211, 1780, 2965, 1983, 1257, 4017, 1255, 2787, 1139,
       1352, 3938, 3050, 2884,  330, 4210,  261, 4008,   79, 3552, 1162,
        239, 4029, 3207, 2168, 2408, 2260,  517, 1744, 3393, 3021, 1303,
       4067, 3299, 2478, 2610, 1388,  466, 1829,  470, 2275, 1586, 2221,
       2181, 2984,  139,  775, 4360, 1675,  178, 3418, 1283, 2970,  535,
       2599,  617,  373, 3343, 4281,  794, 3627, 2833, 3289, 1044, 4108,
       3725, 2153, 2963, 4502,  749, 4453, 4278,  872, 1359,   37, 1053,
       2908, 1795,  212,  952, 2047, 2026, 4322, 4154, 3990,  815, 3367,
        399, 2272,  103, 2296, 2591, 4134,  327,  655,  811, 4407,  847,
       1689, 3905, 1431,  633, 4252, 1084,  909, 29

In [245]:
df_ren.inventory_id.value_counts()

367     1
1769    1
1414    1
2247    1
2968    1
3997    1
87      1
1012    1
3075    1
797     1
3528    1
3677    1
227     1
1027    1
697     1
1150    1
742     1
1273    1
2329    1
4558    1
3741    1
907     1
4147    1
3346    1
3160    1
2038    1
3242    1
1385    1
2441    1
1731    1
1382    1
3226    1
848     1
2846    1
1527    1
1254    1
2465    1
1287    1
58      1
2630    1
1648    1
4213    1
1581    1
2685    1
4204    1
495     1
3548    1
140     1
3105    1
4304    1
3128    1
1922    1
3435    1
3476    1
1781    1
4384    1
739     1
1201    1
126     1
2312    1
331     1
4135    1
2646    1
1525    1
3689    1
3407    1
3770    1
4088    1
933     1
1629    1
242     1
1688    1
3473    1
4124    1
2530    1
2951    1
3084    1
3421    1
769     1
4034    1
2284    1
1183    1
600     1
3189    1
273     1
2528    1
3722    1
581     1
4272    1
1993    1
2803    1
1146    1
730     1
4540    1
1116    1
3687    1
267     1
800     1
635     1
592     1


In [246]:
df_film.film_id.unique()

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [258]:
(df_old.film_id.unique())

array([  1,  23,  25, 106, 140, 166, 277, 361, 438, 499, 506, 509, 605,
       635, 749, 832, 939, 970, 980,   3,  31,  47, 105, 132, 145, 226,
       249, 314, 321, 357, 369, 399, 458, 481, 485, 518, 540, 550, 555,
       561, 742, 754, 811, 958,  17,  40,  42,  87, 111, 185, 289, 329,
       336, 341, 393, 441, 453, 480, 539, 618, 685, 827, 966, 967, 971,
       996,  56,  62,  79, 355, 379, 398, 463, 490, 616, 691, 712, 714,
       721, 798, 858, 909, 924,  19,  54,  85, 146, 171, 172, 202, 203,
       286, 288, 316, 340, 375, 383, 392, 411, 503, 535, 571, 650, 665,
       687, 730, 732, 817, 841, 865,  29,  53,  60,  70, 112, 164, 165,
       193, 256, 451, 517, 519, 692, 826, 892, 902, 994,  27,  35,  67,
        96, 170, 173, 217, 218, 225, 292, 351, 414, 554, 633, 637, 758,
       766, 770, 805, 806, 846, 900, 901, 910, 957, 959, 115, 158, 179,
       195, 205, 255, 263, 396, 523, 532, 752, 769, 771, 859, 895, 936,
        30,  74, 147, 148, 191, 200, 204, 434, 510, 514, 552, 67

In [252]:
df_old.film_id.value_counts()

87     6
321    5
853    5
635    5
146    5
172    5
503    4
453    4
618    4
966    4
1      4
226    4
817    4
112    4
880    4
154    4
536    4
688    4
732    4
280    4
832    4
771    3
717    3
928    3
256    3
201    3
199    3
164    3
34     3
438    3
499    3
119    3
513    3
398    3
583    3
203    3
277    3
144    3
19     3
714    3
427    3
691    3
515    3
335    3
597    3
96     3
236    3
697    3
25     3
873    3
462    3
500    3
752    3
532    3
964    3
9      3
606    3
585    3
179    3
477    3
694    3
716    3
914    3
758    3
637    3
414    3
292    3
463    3
204    3
10     3
23     3
540    3
485    3
17     3
458    3
253    3
369    3
125    3
241    3
111    3
980    3
827    3
793    3
3      3
56     3
502    3
105    3
967    3
811    3
600    3
612    3
431    2
929    2
90     2
856    2
508    2
983    2
429    2
118    2
283    2
764    2
281    2
478    2
908    2
348    2
574    2
904    2
366    2
782    2
43     2
510    2
3

In [249]:
len(df_old.film_id.value_counts())

614

In [253]:
df_old[df_old.film_id == 87]

first_name last_name              title  release_year  category_id  \
47          ED     CHASE  BOONDOCK BALLROOM          2006           16   
71    JENNIFER     DAVIS  BOONDOCK BALLROOM          2006           16   
293        UMA      WOOD  BOONDOCK BALLROOM          2006           16   
384       FRED   COSTNER  BOONDOCK BALLROOM          2006           16   
520    KIRSTEN   PALTROW  BOONDOCK BALLROOM          2006           16   
785     SANDRA      PECK  BOONDOCK BALLROOM          2006           16   

     film_id    complete_name  actor_id  
47        87         ED CHASE         3  
71        87   JENNIFER DAVIS         4  
293       87         UMA WOOD        13  
384       87     FRED COSTNER        16  
520       87  KIRSTEN PALTROW        21  
785       87      SANDRA PECK        30

In [251]:
df_old.drop_duplicates().shape==df_old.shape

True

In [ ]:
df_old.drop_duplicates().shape==df_old.shape

In [255]:
df_old.actor_id.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39], dtype=int64)

In [256]:
df_act.actor_id.unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [260]:
len(df_ren.inventory_id[df_ren.inventory_id < 1000])

212

In [212]:
df_old[df_old.complete_name == 'SUSAN DAVIS']

Empty DataFrame
Columns: [first_name, last_name, title, release_year, category_id, film_id, complete_name, actor_id]
Index: []

In [213]:
df_old[df_old.actor_id == 110]

Empty DataFrame
Columns: [first_name, last_name, title, release_year, category_id, film_id, complete_name, actor_id]
Index: []

In [214]:
df_act.head()

actor_id first_name     last_name        complete_name
0         1   PENELOPE       GUINESS     PENELOPE GUINESS
1         2       NICK      WAHLBERG        NICK WAHLBERG
2         3         ED         CHASE             ED CHASE
3         4   JENNIFER         DAVIS       JENNIFER DAVIS
4         5     JOHNNY  LOLLOBRIGIDA  JOHNNY LOLLOBRIGIDA

In [217]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [218]:
df_film.info(memory_usage='deep')
    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   film_id           1000 non-null   int64  
 1   title             1000 non-null   object 
 2   description       1000 non-null   object 
 3   language_id       1000 non-null   int64  
 4   rental_duration   1000 non-null   int64  
 5   rental_rate       1000 non-null   float64
 6   length            1000 non-null   int64  
 7   replacement_cost  1000 non-null   float64
 8   rating            1000 non-null   object 
 9   special_features  1000 non-null   object 
dtypes: float64(2), int64(4), object(4)
memory usage: 405.5 KB


In [219]:
max_len=0

for i in df_film.special_features:
    if len(i) > max_len:
        max_len = len(i)
        
max_len

54

In [220]:
df_inv.head()

inventory_id  film_id  store_id
0             1        1         1
1             2        1         1
2             3        1         1
3             4        1         1
4             5        1         2

In [221]:
df_lang.head()

language_id      name
0            1   English
1            2   Italian
2            3  Japanese
3            4  Mandarin
4            5    French

In [222]:
df_ren.head()

rental_id          rental_date  inventory_id  customer_id  \
0          1  2005-05-24 22:53:30           367          130   
1          2  2005-05-24 22:54:33          1525          459   
2          3  2005-05-24 23:03:39          1711          408   
3          4  2005-05-24 23:04:41          2452          333   
4          5  2005-05-24 23:05:21          2079          222   

           return_date  staff_id  
0  2005-05-26 22:04:30         1  
1  2005-05-28 19:40:33         1  
2  2005-06-01 22:12:39         1  
3  2005-06-03 01:43:41         2  
4  2005-06-02 04:33:21         1

In [223]:
df_old.head()

first_name last_name                  title  release_year  category_id  \
0   PENELOPE   GUINESS       ACADEMY DINOSAUR          2006            6   
1   PENELOPE   GUINESS   ANACONDA CONFESSIONS          2006            2   
2   PENELOPE   GUINESS            ANGELS LIFE          2006           13   
3   PENELOPE   GUINESS  BULWORTH COMMANDMENTS          2006           10   
4   PENELOPE   GUINESS          CHEAPER CLYDE          2006           14   

   film_id     complete_name  actor_id  
0        1  PENELOPE GUINESS         1  
1       23  PENELOPE GUINESS         1  
2       25  PENELOPE GUINESS         1  
3      106  PENELOPE GUINESS         1  
4      140  PENELOPE GUINESS         1

In [224]:
df_film.head()

film_id             title  \
0        1  ACADEMY DINOSAUR   
1        2    ACE GOLDFINGER   
2        3  ADAPTATION HOLES   
3        4  AFFAIR PREJUDICE   
4        5       AFRICAN EGG   

                                         description  language_id  \
0  A Epic Drama of a Feminist And a Mad Scientist...            1   
1  A Astounding Epistle of a Database Administrat...            1   
2  A Astounding Reflection of a Lumberjack And a ...            1   
3  A Fanciful Documentary of a Frisbee And a Lumb...            1   
4  A Fast-Paced Documentary of a Pastry Chef And ...            1   

   rental_duration  rental_rate  length  replacement_cost rating  \
0                6         0.99      86             20.99     PG   
1                3         4.99      48             12.99      G   
2                7         2.99      50             18.99  NC-17   
3                5         2.99     117             26.99      G   
4                6         2.99     130             22.99      G   

                   special_features  
0  Deleted Scenes,Behind the Scenes  
1           Trailers,Deleted Scenes  
2           Trailers,Deleted Scenes  
3    Commentaries,Behind the Scenes  
4                    Deleted Scenes

In [225]:
df_lang.head()

language_id      name
0            1   English
1            2   Italian
2            3  Japanese
3            4  Mandarin
4            5    French

In [226]:
df_cat.head()

category_id       name
0            1     Action
1            2  Animation
2            3   Children
3            4   Classics
4            5     Comedy

In [227]:
df_inv.iloc[243]

inventory_id    244
film_id          55
store_id          1
Name: 243, dtype: int64

In [228]:
df_film.info('memory usage = deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   film_id           1000 non-null   int64  
 1   title             1000 non-null   object 
 2   description       1000 non-null   object 
 3   language_id       1000 non-null   int64  
 4   rental_duration   1000 non-null   int64  
 5   rental_rate       1000 non-null   float64
 6   length            1000 non-null   int64  
 7   replacement_cost  1000 non-null   float64
 8   rating            1000 non-null   object 
 9   special_features  1000 non-null   object 
dtypes: float64(2), int64(4), object(4)
memory usage: 78.2+ KB


In [229]:
len(df_act.complete_name.value_counts())

199

In [230]:
len(df_old.complete_name.value_counts())

39

In [261]:
df_cat.head

<bound method NDFrame.head of     category_id         name
0             1       Action
1             2    Animation
2             3     Children
3             4     Classics
4             5       Comedy
5             6  Documentary
6             7        Drama
7             8       Family
8             9      Foreign
9            10        Games
10           11       Horror
11           12        Music
12           13          New
13           14       Sci-Fi
14           15       Sports
15           16       Travel>

In [262]:
max(df_old.category_id)

16

In [ ]:
# EXPORTACION 
df_act.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\actor_clean.csv', index=False)
df_cat.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\category_clean.csv', index=False)
df_film.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\film_clean.csv', index=False)
df_inv.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\inventory_clean.csv', index=False)
df_lang.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\language_clean.csv', index=False)
df_old.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\old_HDD_clean.csv', index=False)
df_ren.to_csv(r'C:\Users\david\Proyectos\Github\w3-database-project\data_clean\rental_clean.csv', index=False)